---
- name: Set fact for stats
  set_fact:
    objects_transferred: '{{ final_object_count | int - initial_object_count | int }}'
    bytes_transferred: '{{ final_byte | int - initial_byte | int }}'

- debug:
    msg: |
      Number of bytes transferred: {{ min_byte }}
      Number of objects transferred: {{ objects_transferred }}
    vars:
      min_byte: '{{ bytes_transferred != "0" | ternary (get_byte, "0 Bytes") }}'
      get_byte: '{{ bytes_transferred | human_readable | d () }}'